'use client'

import { Inter } from 'next/font/google'
import './globals.css'
import { ReduxProvider } from '@/app/lib/redux/ReduxProvider';
import { ColorSchemeScript, createTheme } from '@mantine/core';
import '@mantine/core/styles.css';
import MantineProviderCustom from '@/app/ui/MantineProviderCustom';
// import type { Metadata } from 'next'
// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

const inter = Inter({ subsets: ['latin'] })

const theme = createTheme({
  
})


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="en">
        <head>
          <title>App Payment</title>
          <link rel="icon" type="image/x-icon" href="/images/uniclass_logo.png" sizes="any" />
          <ColorSchemeScript />
        </head>
        <body className={inter.className}>
          <ReduxProvider>
            <MantineProviderCustom>
              {children}
            </MantineProviderCustom>
          </ReduxProvider>
        </body>
      </html>
  )
}
